version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "3000:3000"
      - "4280:4280"
    volumes:
      - .:/app
      - /app/__pycache__
    env_file:
      - .env
    command: chainlit run app.py --host 0.0.0.0 --port 8000 